# Generated by Django 4.2.20 on 2025-03-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('organs_to_donate', models.CharField(choices=[('Any part of my body', 'Any part of my body'), ('Lungs', 'Lungs'), ('Blood', 'Blood'), ('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Heart', 'Heart'), ('Eyes', 'Eyes')], max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('mobile_number', models.CharField(max_length=15)),
            ],
        ),
    ]
